### ISSUE TITLE
paper with wrong address

### ISSUE THREAD

**Issue by usperyang** [xingkongliang/Pedestrian-Detection#2]
paper "Adaptive NMS: Refining Pedestrian Detection in a Crowd" with a wrong address. The correct address is https://arxiv.org/pdf/1904.03629.pdf

Anyway, thank the organizers! Thank you very much!

**Comment by xingkongliang** [comment]
> paper "Adaptive NMS: Refining Pedestrian Detection in a Crowd" with a wrong address. The correct address is https://arxiv.org/pdf/1904.03629.pdf
> 
> Anyway, thank the organizers! Thank you very much!

Thanks, the link has been fixed.
